# Generated by Django 5.2.5 on 2025-09-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('history', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
            ],
        ),
    ]
